---
- name: clean proxmox
  file:
    name: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
- name: install epel
  command: yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  args:
    creates: /etc/yum.repos.d/epel.repo
  when: ansible_distribution == "CentOS"
- name: apt update
  command: apt update
  when: ansible_distribution != "CentOS"
- name: install puppet
  package:
    name: puppet
- name: install rsync
  package:
    name: rsync
- name: add ssh key temporarily as sync does not know the password
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
- name: sync puppet
  synchronize:
    src: puppet/
    dest: /tmp/ansible-puppet/
  become: false
- name: remove ssh key
  authorized_key:
    user: root
    state: absent
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
- name: run puppet forcing future parser
  command: puppet apply /tmp/ansible-puppet/site.pp --modulepath=/tmp/ansible-puppet/modules/ --parser future
  when: ansible_distribution == "CentOS"
- name: run puppet
  command: puppet apply /tmp/ansible-puppet/site.pp --modulepath=/tmp/ansible-puppet/modules/
  when: ansible_distribution != "CentOS"
