---
- name: clean proxmox
  file:
    name: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
- name: install epel
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  when: ansible_distribution == "CentOS"
- name: install puppet repo
  yum:
    name: https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
  when: ansible_distribution == "CentOS"
- name: apt update
  command: apt update
  when: ansible_distribution != "CentOS"
- name: install puppet
  package:
    name: puppet
  when: ansible_distribution != "CentOS"
- name: install puppet on CentOS
  package:
    name: puppet-agent
  when: ansible_distribution == "CentOS"
- name: install rsync
  package:
    name: rsync
- name: add ssh key temporarily as sync does not know the password
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: ansible_user == 'root'
- name: sync puppet when root
  synchronize:
    src: puppet/
    dest: /tmp/ansible-puppet/
  become: false
  when: ansible_user == 'root'
- name: sync puppet when not root
  synchronize:
    src: puppet/
    dest: /tmp/ansible-puppet/
    rsync_path: /usr/bin/rsync
  when: ansible_user != 'root'
- name: remove ssh key
  authorized_key:
    user: root
    state: absent
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: ansible_user == 'root'
- name: run puppet
  command: puppet apply /tmp/ansible-puppet/site.pp --modulepath=/tmp/ansible-puppet/modules/
  environment: "{{ puppetenv }}"
  when: ansible_distribution != "CentOS"
- name: run puppet on CentOS
  command: /opt/puppetlabs/bin/puppet apply /tmp/ansible-puppet/site.pp --modulepath=/tmp/ansible-puppet/modules/
  environment: "{{ puppetenv }}"
  when: ansible_distribution == "CentOS"
