---
- name: clean proxmox
  file:
    name: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
- name: install yum repos (epel and puppet5)
  yum:
    name:
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
  when: ansible_distribution == "CentOS"
- name: apt update
  command: apt update
  when: ansible_distribution != "CentOS"
- name: install puppet
  package:
    name: "{% if ansible_distribution == 'CentOS' %}puppet-agent{% else %}puppet{% endif %}"
- name: install rsync
  package:
    name: rsync
- name: add ssh key temporarily as sync does not know the password
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: ansible_user == 'root'
- name: sync puppet when root
  synchronize:
    src: puppet/
    dest: /tmp/ansible-puppet/
    delete: yes
  become: false
  when: ansible_user == 'root'
- name: sync puppet when not root
  synchronize:
    src: puppet/
    dest: /tmp/ansible-puppet/
    rsync_path: /usr/bin/rsync
    delete: yes
  when: ansible_user != 'root'
- name: remove ssh key
  authorized_key:
    user: root
    state: absent
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: ansible_user == 'root'
- name: run puppet
  command: "{% if ansible_distribution == 'CentOS' %}/opt/puppetlabs/bin/{% endif %}puppet apply /tmp/ansible-puppet/site.pp --modulepath=/tmp/ansible-puppet/modules/"
  environment: "{{ puppetenv }}"
  register: puppet_out
- name: view puppet stdout
  debug: var=puppet_out.stdout_lines
- name: view puppet stderr
  debug: var=puppet_out.stderr_lines
