---
- name: clean proxmox
  file:
    name: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent
- name: install dnf plugins core to enable powertools
  package:
    name: dnf-plugins-core
  when: (ansible_distribution == "CentOS" or ansible_distribution == "Rocky") and ansible_distribution_major_version == "8"
- name: enable powertools (required for EPEL 8)
  command: dnf config-manager --set-enabled powertools
  when: (ansible_distribution == "CentOS" or ansible_distribution == "Rocky") and ansible_distribution_major_version == "8"
- name: Import Puppet key
  rpm_key:
    state: present
    key: https://yum.puppet.com/RPM-GPG-KEY-puppet
  when: (ansible_distribution == "CentOS" or ansible_distribution == "Rocky") and ansible_distribution_major_version == "7"
- name: Import EPEL key
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
  when: ansible_distribution == "CentOS" or ansible_distribution == "Rocky"
- name: install epel
  yum:
    name:
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version}}.noarch.rpm
  when: ansible_distribution == "CentOS" or ansible_distribution == "Rocky"
- name: install puppet repo
  yum:
    name:
    - https://yum.puppet.com/puppet5/puppet5-release-el-{{ ansible_distribution_major_version}}.noarch.rpm
  when: (ansible_distribution == "CentOS" or ansible_distribution == "Rocky") and ansible_distribution_major_version == "7"
- name: install puppet repo on ubuntu 16.04
  apt:
    deb: https://apt.puppetlabs.com/puppet7-release-xenial.deb
    state: present
  when: ansible_distribution_release == 'xenial'
- name: apt update
  command: apt update
  when: ansible_distribution != "CentOS" and ansible_distribution != "Rocky"
- name: install puppet and rsync
  package:
    name:
    - "{% if ((ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky') and ansible_distribution_major_version == '7') or ansible_distribution_release == 'xenial' %}puppet-agent{% else %}puppet{% endif %}"
    - rsync
- name: disable puppet service
  service:
    name: puppet
    enabled: no
- name: add ssh key temporarily as sync does not know the password
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: ansible_user | default('notroot') == 'root'
  tags: fast
- name: sync puppet when root
  synchronize:
    src: puppet/
    dest: /tmp/ansible-puppet/
    delete: yes
  become: false
  when: ansible_user | default('notroot') == 'root'
  tags: fast
- name: sync puppet when not root
  synchronize:
    src: puppet/
    dest: /tmp/ansible-puppet/
    rsync_path: /usr/bin/rsync
    delete: yes
  when: ansible_user | default('notroot') != 'root'
  tags: fast
- name: remove ssh key
  authorized_key:
    user: root
    state: absent
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: ansible_user | default('notroot') == 'root'
  tags: fast
- name: run puppet
  command: "{% if ((ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky') and ansible_distribution_major_version == '7') or ansible_distribution_release == 'xenial' %}/opt/puppetlabs/bin/{% endif %}puppet apply /tmp/ansible-puppet/site/ --modulepath=/tmp/ansible-puppet/modules/"
  environment: "{{ lookup('vars', 'puppetenv', default={}) | combine(lookup('vars', 'puppetenv_host', default={})) }}"
  register: puppet_out
  tags: fast
- name: view puppet stdout
  debug: var=puppet_out.stdout_lines
  tags: fast
- name: view puppet stderr
  debug: var=puppet_out.stderr_lines
  tags: fast
- name: run puppet twice as some facts are not properly detected the first time
  command: "{% if ((ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky') and ansible_distribution_major_version == '7') or ansible_distribution_release == 'xenial' %}/opt/puppetlabs/bin/{% endif %}puppet apply /tmp/ansible-puppet/site/ --modulepath=/tmp/ansible-puppet/modules/"
  environment: "{{ lookup('vars', 'puppetenv', default={}) | combine(lookup('vars', 'puppetenv_host', default={})) }}"
  register: puppet_out
- name: view puppet stdout twice
  debug: var=puppet_out.stdout_lines
- name: view puppet stderr twice
  debug: var=puppet_out.stderr_lines
